<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ibm.cicsdev</groupId>
    <artifactId>cics-java-liberty-kafka</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>CICS Kafka Jakarta EE</name>
    <description>Sample CICS application demonstrating Kafka consumption using Jakarta EE, MicroProfile, and IBM Liberty, integrated with CICS.</description>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <cics.jvmserver>DFHWLP</cics.jvmserver>
        <cics.bom.version>6.1-20250812133513-PH63856</cics.bom.version>

        <jakarta.version>10.0.0</jakarta.version>
        <microprofile.version>7.0</microprofile.version>
        <microprofile.reactive.messaging.version>3.0</microprofile.reactive.messaging.version>
        <liberty.apis.version>25.0.0.9</liberty.apis.version>

        <kafka.version>4.0.1</kafka.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.ibm.cics</groupId>
                <artifactId>com.ibm.cics.ts.bom</artifactId>
                <version>${cics.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>cics-java-liberty-kafka-app</module>
        <module>cics-java-liberty-kafka-cicsbundle</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
