// ============================================================================
// Root Project Configuration
// ============================================================================
rootProject.name = 'cics-java-liberty-kafka'

// ============================================================================
// Subprojects
// ============================================================================
include(':cics-java-liberty-kafka-app')
include(':cics-java-liberty-kafka-bundle')