plugins {
    id 'com.ibm.cics.bundle' version '1.0.8'
}

description = 'CICS Kafka Jakarta EE Application - CICS Bundle'
version = '1.0.0'

dependencies {
    cicsBundlePart project(path: ':cics-java-liberty-kafka-app', configuration: 'archives')
}

cicsBundle {
    build {
        defaultJVMServer = project.findProperty("cics.jvmserver") ?: "DFHWLP"
    }
}
