bootstrap.servers=9.43.10.105:9092

# Define a Kafka consumer channel called "test-topic"
test-topic.connector=liberty-kafka
test-topic.topic=test-topic
test-topic.group.id=cics-java-group
test-topic.auto.offset.reset=earliest
test-topic.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
test-topic.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configuration to select which CICS transaction id we want to process messages on
cics.transaction.map.test-topic=KAFK