###############################################################################
# NOTE ON - VPN CONNECTIVITY
#
# When VPN is connected, the active interface is usually utunX or vpnX (e.g. utun4/vpn0).
# Example VPN IP:
#   ifconfig / ip addr show -> utun4 / vpn0 -> inet x.xx.xx.xxx
#
# Kafka bootstrap.servers must point to a broker address reachable via VPN.
bootstrap.servers=x.x.x.x:9092

# Define a Kafka consumer channel called "test-topic"
test-topic.connector=liberty-kafka
test-topic.topic=test-topic
test-topic.group.id=cics-java-group
test-topic.auto.offset.reset=earliest
test-topic.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
test-topic.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configuration to select which CICS transaction id we want to process messages on
cics.transaction.map.test-topic=KAFK